# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WongYiuNam-Doctor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WongYiuNam-Doctor
  pod 'Moya'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Moya-ObjectMapper'
  pod 'IBAnimatable'
  pod 'Firebase'
  pod 'SVProgressHUD'
  pod 'Firebase/Messaging'
  pod 'SDWebImage'
  pod 'DateToolsSwift'
  
  target 'WongYiuNam-DoctorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WongYiuNam-DoctorUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  swift3Pods = ["ObjectMapper"]
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
          # these libs work now only with Swift3.2 in Xcode9
          if swift3Pods.include? target.name
              configuration.build_settings['SWIFT_VERSION'] = "3.2"
          end
      end
  end
end
