# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WongYiuNam-Doctor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WongYiuNam-Doctor

  target 'WongYiuNam-DoctorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WongYiuNam-DoctorUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod ‘Moya’ 
pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod 'Moya-ObjectMapper'
pod 'IBAnimatable'
end
