# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WongYiuNam-Doctor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WongYiuNam-Doctor
  pod 'Moya'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'Moya-ObjectMapper'
  pod 'IBAnimatable'
  pod 'Firebase'
  pod ‘SVProgressHUD’
  pod 'Firebase/Messaging'
  pod 'SDWebImage'
  pod 'JVFloatLabeledTextField'
  target 'WongYiuNam-DoctorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WongYiuNam-DoctorUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
