platform :ios, '9.0'
use_frameworks!

target 'WongYiuNam-User' do
    pod 'SDWebImage'
    pod 'SlideMenuControllerSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'LTHRadioButton'
    pod 'Moya'
    pod 'Moya-ModelMapper'
    pod 'SwiftyButton'
    pod 'DRPLoadingSpinner'
end
