platform :ios, '9.0'
use_frameworks!

target 'WongYiuNam-User' do
    pod 'SDWebImage'
    pod 'SlideMenuControllerSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'LTHRadioButton'
    pod 'Moya-ObjectMapper'
    pod 'DRPLoadingSpinner'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'UILoadControl'
    pod 'PopupDialog'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            # these libs work now only with Swift3.2 in Xcode9
            if ['FacebookCore'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['FacebookLogin'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['ObjectMapper'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['PopupDialog'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['RxCocoa'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['RxSwift'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['SlideMenuControllerSwift'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
            if ['SwiftyButton'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
        end
    end
end
